require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PredefinedTagsController do

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PredefinedTagsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all predefined_tags as @predefined_tags" do
      predefined_tag = FactoryGirl.create(:predefined_tag)
      get :index, {}, valid_session
      assigns(:predefined_tags).should eq([predefined_tag])
    end
  end

  describe "GET show" do
    it "assigns the requested predefined_tag as @predefined_tag" do
      predefined_tag = FactoryGirl.create(:predefined_tag)
      get :show, {:id => predefined_tag.to_param}, valid_session
      assigns(:predefined_tag).should eq(predefined_tag)
    end
  end

  describe "GET new" do
    it "assigns a new predefined_tag as @predefined_tag" do
      get :new, {}, valid_session
      assigns(:predefined_tag).should be_a_new(PredefinedTag)
    end
  end

  describe "GET edit" do
    it "assigns the requested predefined_tag as @predefined_tag" do
      predefined_tag = FactoryGirl.create(:predefined_tag)
      get :edit, {:id => predefined_tag.to_param}, valid_session
      assigns(:predefined_tag).should eq(predefined_tag)
    end
  end

  describe "POST create" do
    before do
      @predefined_tag = FactoryGirl.attributes_for(:predefined_tag)
    end
    describe "with valid params" do
      it "creates a new PredefinedTag" do
        expect {
          post :create, {:predefined_tag => @predefined_tag}, valid_session
        }.to change(PredefinedTag, :count).by(1)
      end

      it "assigns a newly created predefined_tag as @predefined_tag" do
        post :create, {:predefined_tag => @predefined_tag}, valid_session
        assigns(:predefined_tag).should be_a(PredefinedTag)
        assigns(:predefined_tag).should be_persisted
      end

      it "redirects to the created predefined_tag" do
        post :create, {:predefined_tag => @predefined_tag}, valid_session
        response.should redirect_to(PredefinedTag.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved predefined_tag as @predefined_tag" do
        # Trigger the behavior that occurs when invalid params are submitted
        PredefinedTag.any_instance.stub(:save).and_return(false)
        post :create, {:predefined_tag => {}}, valid_session
        assigns(:predefined_tag).should be_a_new(PredefinedTag)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PredefinedTag.any_instance.stub(:save).and_return(false)
        post :create, {:predefined_tag => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested predefined_tag" do
        predefined_tag = FactoryGirl.create(:predefined_tag)
        # Assuming there are no other predefined_tags in the database, this
        # specifies that the PredefinedTag created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PredefinedTag.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => predefined_tag.to_param, :predefined_tag => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested predefined_tag as @predefined_tag" do
        predefined_tag = FactoryGirl.create(:predefined_tag)
        valid_attributes = FactoryGirl.attributes_for(:predefined_tag)
        put :update, {:id => predefined_tag.to_param, :predefined_tag => valid_attributes}, valid_session
        assigns(:predefined_tag).should eq(predefined_tag)
      end

      it "redirects to the predefined_tag" do
        predefined_tag = FactoryGirl.create(:predefined_tag)
        valid_attributes = FactoryGirl.attributes_for(:predefined_tag)
        put :update, {:id => predefined_tag.to_param, :predefined_tag => valid_attributes}, valid_session
        response.should redirect_to(predefined_tag)
      end
    end

    describe "with invalid params" do
      it "assigns the predefined_tag as @predefined_tag" do
        predefined_tag = FactoryGirl.create(:predefined_tag)
        # Trigger the behavior that occurs when invalid params are submitted
        PredefinedTag.any_instance.stub(:save).and_return(false)
        put :update, {:id => predefined_tag.to_param, :predefined_tag => {}}, valid_session
        assigns(:predefined_tag).should eq(predefined_tag)
      end

      it "re-renders the 'edit' template" do
        predefined_tag = FactoryGirl.create(:predefined_tag)
        # Trigger the behavior that occurs when invalid params are submitted
        PredefinedTag.any_instance.stub(:save).and_return(false)
        put :update, {:id => predefined_tag.to_param, :predefined_tag => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested predefined_tag" do
      predefined_tag = FactoryGirl.create(:predefined_tag)
      expect {
        delete :destroy, {:id => predefined_tag.to_param}, valid_session
      }.to change(PredefinedTag, :count).by(-1)
    end

    it "redirects to the predefined_tags list" do
      predefined_tag = FactoryGirl.create(:predefined_tag)
      delete :destroy, {:id => predefined_tag.to_param}, valid_session
      response.should redirect_to(predefined_tags_url)
    end
  end

end
